import './globals.css';
import Providers from './components/Providers';
import MyAppBar from './components/AppBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <MyAppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
